version: '3.8'
services:
  # Тестовый "заглушка"-сервер, который просто отвечает 200 OK
  test-echo-server:
    image: hashicorp/http-echo
    command: -text="OK" -listen=:8080
    ports:
      - "9999:8080"

  # Тестовый клиент для нагрузки (k6)
  load-tester:
    image: grafana/k6:latest
    volumes:
      - ./test-script.js:/test.js
    command: run /test.js
    depends_on:
      - test-echo-server

  # Мониторинг ресурсов
  resource-monitor:
    image: alpine:latest
    command: sh -c "apk add --no-cache htop && htop"
    privileged: true
    tty: true